### PR TITLE
Improved Navbar mentioned in #5 issue

### PR DESCRIPTION
**Pull request by Nandini80**
I have made some necessary changes in Sidebar.css and in HomePage.css to make it look more convincing.
Kindly review the changes

### CODE REVIEW

**Comment by PranabKumarSahoo** [comment]
Hello @Nandini80,

Thanks for your contribution. ⭐
Make sure to keep me update your changes through images/videos in the comment section before you raise the PR.
For real-time communication, you can join the [Discord](https://discord.gg/TSYH66px) [Find **#sql-dev-tools** channel].

**#Good Luck!✌️**

**Comment by singodiyashubham87** [comment]
@Nandini80 Always mention the issue number in your PR in the following format: 
Resolve issue #<issue_number>

**Comment by Nandini80** [comment]
Will keep that in mind. Thanks for the guidance.

**Comment by PranabKumarSahoo** [comment]
Hi @Nandini80,

Can you simply show your changes through images/videos here!? It would be great to ensure a thorough review and make the integration process smoother.

**Thank you! ✌️**

**Comment by Nandini80** [comment]
After implementing some adjustments, here's the updated look. Take a look and let me know your thoughts on the recent changes.

image

**Comment by PranabKumarSahoo** [comment]
Good job @Nandini80! ⭐

I reviewed it & looks nice. So I'm merging the PR.

Feel free to create another issues & start contributing it.

---
**#Good Luck! ✌️**

**Pull request merged**
