### PR TITLE
create CONTRIBUTING.md file 

### PR DESCRIPTION
**Pull request by ARSHIA03**
I have created CONTRIBUTING.md file. New contributors can access the guidelines before starting their contributions.

### CODE REVIEW

**Comment by PranabKumarSahoo** [comment]
Hello @ARSHIA03,

Thank you for creating the **CONTRIBUTING.md** file. Your effort is highly appreciated. 
I will review it shortly and provide feedback if there are any suggested changes. Your contribution in making the guidelines accessible for new contributors is invaluable.

Additionally, I would like to seek assistance from our mentor for the review process. @singodiyashubham87, would you kindly help in reviewing the **CONTRIBUTING.md** file? Your insights will greatly contribute to ensuring the effectiveness and clarity of our guidelines.

I appreciate the collaborative effort from both of you.

**Thank You! ✌️**

**Comment by singodiyashubham87** [comment]
@ARSHIA03 I have done the initial review & here is my feedback:

1. Always mention which issue number your PR resolves in the PR description in this format -> Resolve issue <issue_number>
2. It will be better if you add standard commit guidelines in the bottom part of the file.

**Comment by PranabKumarSahoo** [comment]
Thank you @singodiyashubham87 for your cooperation, 
I've received initial feedback from you.

@ARSHIA03, 
Kindly consider incorporating these suggestions into your pull request. Once you've made the changes, let me know, and I'll coordinate the final review.

**#Good Luck! ✌️**

**Comment by PranabKumarSahoo** [comment]
@singodiyashubham87,
Thank you for your prompt and thorough review of the **CONTRIBUTING.md** file. Your feedback is invaluable in enhancing the clarity and effectiveness of our guidelines.

So, @ARSHIA03 made the necessary changes as per your suggestions. The pull request has been updated to address the feedback, and we are ready for the final review.

If you have any further insights or if there are additional steps you recommend, please let us know.

**Thanks again for your support!⭐**

**Pull request merged**
