### PR TITLE
Added the responsive contact us page by Parmesh B

### PR DESCRIPTION
**Pull request by parmesh-bhatt**
Issue no. #31 

@PranabKumarSahoo, I have added the contact us page and also make it responsive.
Please check it and If It is fine then please merge it to the main branch.

### CODE REVIEW

**Comment by parmesh-bhatt** [comment]
@PranabKumarSahoo, I think now its perfect.

screen shot
Screenshot from 2024-01-11 14-11-14

**Comment by PranabKumarSahoo** [comment]
Nice work @Parmesh119,

I'll review your code in shortly. Till then feel free to create issues/contribute more. ✌️

**Thanks for the contribution.**

**Comment by PranabKumarSahoo** [comment]
Hello @Parmesh119,

Thank you for your contribution in adding the contact us page and making it responsive. I appreciate your effort in enhancing our project.

I've noticed that the changes were made using `Bootstrap`, whereas our website is primarily built using **Pure CSS**. 
To maintain consistency in our project, I generally prefer using the existing styling approach. Could you kindly make the adjustments to match the styling conventions of our project? 
If you have any questions or need guidance on adapting the styling, feel free to ask.

Additionally, I apologize for the delay in reviewing your code. I've been quite busy these days. I'll make sure to review it at the earliest.

Thank you for your understanding, and I look forward to your continued contributions.

---
**#Good Luck! ✌️**

**Comment by parmesh-bhatt** [comment]
@PranabKumarSahoo, Actually my laptop is little bit damaged. So, it's in the repairing. So, I would make the change in a soon.

**Comment by parmesh-bhatt** [comment]
@PranabKumarSahoo, Now its fine I think. Just review it.

**Comment by PranabKumarSahoo** [comment]
Hello @Parmesh119,

Thank you for your effort in adding the contact us page and making it responsive. I've reviewed the changes you made in the pull request.

## First of all watch these two video demo of our recent version & your version updates!
**Recent Version**

https://github.com/PranabKumarSahoo/sql-dev-tools/assets/118038201/3abc4d3f-d78a-41d4-a337-bc022260ec26



**Your Version**

https://github.com/PranabKumarSahoo/sql-dev-tools/assets/118038201/88346d6b-f2b5-4bcc-9393-9b9dcdc39998

I noticed a few areas that need attention for correct integration with our project's styling conventions. So here's some concerns:

- **Navigation and Scroll:**
In your updated version repo, there seem to be issues with the navigation and scrolling functionality. The sidebar doesn't even work with functional links, and there is no scroll-to-top button as well. It's essential to ensure a seamless user experience with proper navigation.

- **Section Visibility:**
The homepage only displays the first section, and subsequent sections are not visible. It's crucial to address this to present all sections appropriately.

- **Button Design:**
The design of buttons, especially in the contact form, could be adjusted to match the existing button design component in our recent version repository. And also you can see in the video, the output `copy` button is align in the bottom of the output box, but in the recent version of our project repo, the buttons are align in the top right corner. You need to fix in your version.

So, I provided these video demonstration highlighting the changes you made in your version and compare it with the recent version available in the repository. This will help in better understanding the differences and addressing the concerns effectively. Right!

Feel free to ask for any clarification or guidance during the process. Your contributions are valued, and I look forward to seeing the improvements.

Thank you for your understanding and continued efforts.

#Good Luck! ✌️

**Pull request closed without merging**
