### PR TITLE
scrollBar style enhanced

### LINKED ISSUE #1: Enhancing style of scrollBar
While the site boasts an interactive and captivating interface, I believe introducing a more refined navbar would elevate its elegance further. I am eager to enhance this aspect and contribute to a seamless and visually appealing user experience.

### PR DESCRIPTION
**Pull request by Akshanshkaushal**
Scroll bar style changed as per the design of the site
issue resolved #1

### CODE REVIEW

**Comment by Akshanshkaushal** [comment]
Tell me the required changes.

**Comment by PranabKumarSahoo** [comment]
I think the scrollbar-track needs to improve, as per you design, you can see there's a small white color in the track corners.
Either You can remove the track radius or you can simply make the track background-color to transparent.

Hope you get it!

**If you still have any doubts, feel free to ask.**
**#Good Luck!✌️**

**Comment by Akshanshkaushal** [comment]
Sure , I'm working upon it

**Comment by Akshanshkaushal** [comment]
Fixed the issue
Screenshot (177)

**Comment by PranabKumarSahoo** [comment]
Cool @Akshanshkaushal! ⭐
As per the **SWOC Rules**, it begins on 1st Jan 2024! 
So don't worry I'll merge the PR at the beginning of New Year!!😊

---
**Feel free to contribute to another issues which is now opened.**

**Thank You!✌️**

**Pull request merged**
