### PR TITLE
Added toastify notification on submit and copy button

### PR DESCRIPTION
**Pull request by Anubhab-03**
## Fixes Issue
Solves Issue #2 

## Description
- Added pop-up notification to **Submit** button and **Copy** button.
- On successful/wrong submission message is displayed accordingly.
- The copy button changes to a green tick for 2 seconds on successful text copy.

## Tech Stack Used
- Used **React - Toastify** library of ReactJS to implement appropriate notifications.

## Additional changes
- Set the default color of the copy button to **red** so that it looks good when it changes to **green tick**.

## Screenshots
Screenshot 2024-01-04 162005

Screenshot 2024-01-04 162107

Screenshot 2024-01-04 162119

### CODE REVIEW

**Comment by Anubhab-03** [comment]
@PranabKumarSahoo kindly go through the changes made and accept the PR if found alright

**Comment by PranabKumarSahoo** [comment]
Hi @Anubhab-03,

Excellent work on adding the Toastify notification feature to the Submit and Copy buttons for all sections! 👏
That looks great but If the Tostify Notification could be shown in Top Right corner, It'd be more seamless user experience. Right!!

After changes, You can raise the PR. Then I'll merge it. No issues.

**#Good Luck! ✌️**

**Comment by PranabKumarSahoo** [comment]
Good job @Anubhab-03,

I'm merging the PR. Thanks for the contribution. ⭐

---
Feel free to create/work on more issues.

**#Good luck! ✌️**

**Comment by Anubhab-03** [comment]
Thanks a lot, @PranabKumarSahoo for merging the PR. I enjoyed contributing to your project!!

**Comment by Anubhab-03** [comment]
Just a query, any idea how will the points be awarded and where to check the leaderboard

**Comment by PranabKumarSahoo** [comment]
I guess the scores will be counted as per the **Quine DevRank Points** & for the **Leaderboard**, there might be released after the end of the program i think.

For clarification, You can ask our mentors in the [Discord](https://discord.gg/TSYH66px) project channel.

**Pull request merged**
