### PR TITLE
Resolve Issue: #33 BUG-Fix: overlapping of drop constraints and count row 

### PR DESCRIPTION
**Pull request by kherkatary**
# Resolve issue: #33 Overlapping of differnet Sections in diffrent scaling of screens
### Changes made :
- section height fit according to height
- targeting each section with same class inorder to reduce the code complexity and keep the design uniform
- removed IDs of each section that were changing the css of each section individually, and fixed it by using same class for each

### BUG : - The count overlaps with the drop section
issue_2

### Resolved BUG : -
issue_fix

### CODE REVIEW

**Comment by PranabKumarSahoo** [comment]
Hello @kherkatary,

Thank you for your contribution and the changes you made to address the issue #33 regarding the overlapping of sections on different screen scalings. I appreciate your efforts in improving the codebase.

Upon reviewing the changes, I noticed that in `HomePage.jsx`, the IDs associated with each section were removed. 
While your intention to reduce code complexity is commendable, it's important to consider the functionality associated with these IDs, particularly for smooth navigation.

The previous IDs were utilized for linking purposes, enabling users to navigate directly to a specific section by clicking on the corresponding link in the navbar. With the removal of these IDs, this functionality might be affected.

I recommend considering a solution that maintains both the code simplicity and the expected functionality. So, make sure to test everything before submitting the PRs.

Please review this aspect, and if needed, we can discuss further more.

Thank you for your understanding, and I look forward to your continued contributions.

---
**#Good Luck! ✌️**

**Comment by kherkatary** [comment]
Okay Thank you, I will work on it

**Comment by kherkatary** [comment]
The navigation from the side-bar to the individual section is not working in my laptop. So it slipped through. But unlike the one deployed in the server where the navigation works fine, when i clone it, the navigation doesnt work in my laptop.
Can you suggest any solution?. I cloned it again but still same issue.

**Comment by PranabKumarSahoo** [comment]
Hello @kherkatary,

I understand the challenge you're facing with the navigation from the side-bar not working on your laptop.

But, I've cloned the recent repository on my device, and I've created a short video demonstrating the navigation working correctly. You can view the video here:

https://github.com/PranabKumarSahoo/sql-dev-tools/assets/118038201/967f975b-e2b0-42f8-9cba-b0a0127a4760

### Try to check your code again.

**Comment by kherkatary** [comment]
Hey @PranabKumarSahoo , can you once review with my lastet commit, i restored the original code in home.js and have made changes only in one file, Home.css, and only the heights are changes. The changes should remove the overlapping bug while keeping the navigation part untouched.

**Comment by PranabKumarSahoo** [comment]
Cool @kherkatary! ⭐
Good job. I'm merging the PR now.

Thanks for the contribution. Feel free to contribute more.

----
**#Good Luck! ✌️**

**Comment by kherkatary** [comment]
@PranabKumarSahoo  Thank You :smile:

**Pull request merged**
